---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec
  format: doc

platforms:
  - name: debian-9

suites:
  - name: default
    run_list:
      - recipe[debian-sid::default]
    attributes:
